package com.mars.simpleepubreader;

import android.app.*; import android.os.*; import android.content.*; import android.net.*; import android.view.*; import android.webkit.*;
import org.xmlpull.v1.*;
import java.io.*; import java.util.*; import java.util.zip.*;

public class MainActivity extends Activity {
  static final int PICK=7; ReaderWebView w; File root; ArrayList<File> spine=new ArrayList<>(); int chap=0;
  static final String CSS="<style>html,body{background:#fff!important;color:#000!important}html{height:100%;overflow:hidden}body{-webkit-writing-mode:vertical-rl!important;writing-mode:vertical-rl!important;text-orientation:mixed!important;height:calc(100vh - 20px)!important;margin:0!important;padding:10px 16px!important;font:22px/1.8 serif!important;overflow:visible!important}*{-webkit-user-select:none!important;user-select:none!important;-webkit-touch-callout:none!important;animation:none!important;transition:none!important;text-shadow:none!important}ruby{ruby-position:over!important}rt{font-size:.5em!important}a{color:#000!important;text-decoration:none!important}img,svg{max-height:85vh!important;max-width:75vw!important}</style>";
  public void onCreate(Bundle b){super.onCreate(b);getWindow().setFlags(1024,1024);w=new ReaderWebView(this);setContentView(w);setup();root=new File(getFilesDir(),"book");Uri u=getIntent()==null?null:getIntent().getData();if(u!=null)open(u);else if(loadList())show(0);else pick();}
  void setup(){w.setBackgroundColor(0xffffffff);w.setHorizontalScrollBarEnabled(false);w.setVerticalScrollBarEnabled(false);w.setLongClickable(false);WebSettings s=w.getSettings();s.setJavaScriptEnabled(false);s.setAllowFileAccess(true);s.setBlockNetworkLoads(true);s.setSupportZoom(false);s.setDefaultFontSize(22);w.setOnLongClickListener(v->true);w.setOnTouchListener(new View.OnTouchListener(){float x;public boolean onTouch(View v,android.view.MotionEvent e){if(e.getAction()==0)x=e.getX();if(e.getAction()==1&&Math.abs(e.getX()-x)<40){if(e.getX()<w.getWidth()/2f)next();else prev();}return true;}});}
  void pick(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("application/epub+zip");try{startActivityForResult(i,PICK);}catch(Exception e){i.setType("*/*");startActivityForResult(i,PICK);}}
  protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(r==PICK&&c==RESULT_OK&&d!=null)open(d.getData());}
  void open(Uri u){try{del(root);root.mkdirs();File z=new File(root,"book.epub"),dir=new File(root,"x");dir.mkdirs();copy(getContentResolver().openInputStream(u),new FileOutputStream(z));unzip(z,dir);parse(dir);saveList();chap=0;show(0);}catch(Exception e){msg("Could not open EPUB: "+e.getMessage());}}
  void show(int i){if(spine.isEmpty())return;chap=Math.max(0,Math.min(i,spine.size()-1));try{File f=spine.get(chap);String h=read(f).replaceAll("(?is)<script\\b[^>]*>.*?</script\\s*>","");h=h.matches("(?is).*?</head>.*")?h.replaceFirst("(?i)</head>",CSS+"</head>"):CSS+h;w.loadDataWithBaseURL(Uri.fromFile(f.getParentFile()).toString()+"/",h,"text/html","UTF-8",null);}catch(Exception e){msg(e.toString());}}
  void next(){int x=w.getScrollX(),step=Math.max(1,w.getWidth());if(x>2)w.scrollTo(Math.max(0,x-step),0);else if(chap+1<spine.size())show(chap+1);}
  void prev(){int max=Math.max(0,w.range()-w.getWidth()),step=Math.max(1,w.getWidth());if(w.getScrollX()<max-2)w.scrollTo(Math.min(max,w.getScrollX()+step),0);else if(chap>0){show(chap-1);w.postDelayed(()->w.scrollTo(Math.max(0,w.range()-w.getWidth()),0),250);}}
  public boolean onKeyDown(int k,KeyEvent e){if(k==KeyEvent.KEYCODE_VOLUME_DOWN||k==KeyEvent.KEYCODE_PAGE_DOWN||k==KeyEvent.KEYCODE_DPAD_LEFT){next();return true;}if(k==KeyEvent.KEYCODE_VOLUME_UP||k==KeyEvent.KEYCODE_PAGE_UP||k==KeyEvent.KEYCODE_DPAD_RIGHT){prev();return true;}if(k==KeyEvent.KEYCODE_MENU){pick();return true;}return super.onKeyDown(k,e);}
  void parse(File base)throws Exception{spine.clear();XmlPullParserFactory f=XmlPullParserFactory.newInstance();XmlPullParser p=f.newPullParser();File c=new File(base,"META-INF/container.xml");p.setInput(new FileInputStream(c),null);String op=null;for(int e=p.getEventType();e!=XmlPullParser.END_DOCUMENT;e=p.next())if(e==XmlPullParser.START_TAG&&"rootfile".equals(p.getName())){op=p.getAttributeValue(null,"full-path");break;}if(op==null)throw new Exception("No OPF");File of=new File(base,Uri.decode(op)).getCanonicalFile();HashMap<String,String> m=new HashMap<>();ArrayList<String> o=new ArrayList<>();p=f.newPullParser();p.setInput(new FileInputStream(of),null);for(int e=p.getEventType();e!=XmlPullParser.END_DOCUMENT;e=p.next())if(e==XmlPullParser.START_TAG){if("item".equals(p.getName()))m.put(p.getAttributeValue(null,"id"),p.getAttributeValue(null,"href"));if("itemref".equals(p.getName()))o.add(p.getAttributeValue(null,"idref"));}for(String id:o){String h=m.get(id);if(h==null)continue;int q=h.indexOf('#');if(q>=0)h=h.substring(0,q);File x=new File(of.getParentFile(),Uri.decode(h)).getCanonicalFile();if(x.isFile()&&x.getPath().startsWith(base.getCanonicalPath()+File.separator))spine.add(x);}if(spine.isEmpty())throw new Exception("No readable spine");}
  void unzip(File z,File out)throws Exception{String base=out.getCanonicalPath()+File.separator;ZipInputStream in=new ZipInputStream(new BufferedInputStream(new FileInputStream(z)));ZipEntry e;byte[] b=new byte[16384];while((e=in.getNextEntry())!=null){File f=new File(out,e.getName());if(!f.getCanonicalPath().startsWith(base))throw new Exception("Unsafe EPUB path");if(e.isDirectory())f.mkdirs();else{f.getParentFile().mkdirs();FileOutputStream o=new FileOutputStream(f);int n;while((n=in.read(b))>0)o.write(b,0,n);o.close();}}in.close();}
  void saveList()throws Exception{FileWriter fw=new FileWriter(new File(root,"spine.txt"));File base=new File(root,"x");for(File f:spine)fw.write(f.getCanonicalPath().substring(base.getCanonicalPath().length()+1)+"\n");fw.close();}
  boolean loadList(){try{File base=new File(root,"x"),l=new File(root,"spine.txt");if(!l.isFile())return false;BufferedReader r=new BufferedReader(new FileReader(l));String s;while((s=r.readLine())!=null){File f=new File(base,s);if(f.isFile())spine.add(f);}r.close();return !spine.isEmpty();}catch(Exception e){return false;}}
  static void copy(InputStream i,OutputStream o)throws Exception{byte[] b=new byte[16384];int n;while((n=i.read(b))>0)o.write(b,0,n);i.close();o.close();}
  static String read(File f)throws Exception{BufferedReader r=new BufferedReader(new InputStreamReader(new FileInputStream(f),"UTF-8"));StringBuilder b=new StringBuilder();char[] c=new char[8192];int n;while((n=r.read(c))>0)b.append(c,0,n);r.close();return b.toString();}
  static void del(File f){if(!f.exists())return;if(f.isDirectory()){File[] a=f.listFiles();if(a!=null)for(File x:a)del(x);}f.delete();}
  void msg(String s){w.loadData("<meta charset=utf-8><body style='font:20px sans-serif;padding:10%'>"+s.replace("<","&lt;")+"</body>","text/html","UTF-8");}
  static class ReaderWebView extends WebView{ReaderWebView(Activity a){super(a);}int range(){return computeHorizontalScrollRange();}}
}
