package com.mars.simpleepubreader;

import android.app.*;import android.os.*;import android.content.*;import android.content.pm.PackageManager;import android.net.*;import android.graphics.*;import android.view.*;import android.widget.*;
import org.xmlpull.v1.*;import java.io.*;import java.util.*;import java.util.zip.*;

public class MainActivity extends Activity{
 static final int PICK=7, STORAGE=8; File root; ArrayList<File> spine=new ArrayList<>(); Reader reader; int chap=0; Uri pendingUri; boolean pendingPick=false;
 public void onCreate(Bundle b){super.onCreate(b);root=new File(getFilesDir(),"book");Uri u=getIntent()==null?null:getIntent().getData();if(u!=null)openOrRequest(u);else if(loadList()){chap=getPreferences(0).getInt("chap",0);show(chap,getPreferences(0).getInt("off",0));}else home(null);}
 void home(String note){reader=null;LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setGravity(Gravity.CENTER);l.setPadding(30,30,30,30);l.setBackgroundColor(Color.WHITE);TextView t=new TextView(this);t.setText("Simple EPUB Reader\nLikebook Mars · Android 6"+(note==null?"":"\n\n"+note));t.setTextColor(Color.BLACK);t.setTextSize(21);t.setGravity(Gravity.CENTER);l.addView(t);Button b=new Button(this);b.setText("OPEN EPUB");b.setTextSize(18);b.setOnClickListener(v->pick());LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(260,70);p.setMargins(0,35,0,0);l.addView(b,p);setContentView(l);}
 void loading(String s){TextView t=new TextView(this);t.setText(s);t.setTextSize(20);t.setTextColor(Color.BLACK);t.setBackgroundColor(Color.WHITE);t.setGravity(Gravity.CENTER);setContentView(t);}
 boolean canReadStorage(){return Build.VERSION.SDK_INT<23||checkSelfPermission(android.Manifest.permission.READ_EXTERNAL_STORAGE)==PackageManager.PERMISSION_GRANTED;}
 void pick(){if(!canReadStorage()){pendingPick=true;requestPermissions(new String[]{android.Manifest.permission.READ_EXTERNAL_STORAGE},STORAGE);return;}doPick();}
 void doPick(){pendingPick=false;Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("application/epub+zip");i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION);try{startActivityForResult(i,PICK);}catch(Throwable e){try{i=new Intent(Intent.ACTION_GET_CONTENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("*/*");i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);startActivityForResult(i,PICK);}catch(Throwable x){home("No file picker found. Open an EPUB from the file manager.");}}}
 protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(r==PICK&&c==RESULT_OK&&d!=null&&d.getData()!=null){Uri u=d.getData();try{if("content".equals(u.getScheme()))getContentResolver().takePersistableUriPermission(u,Intent.FLAG_GRANT_READ_URI_PERMISSION);}catch(Throwable ignored){}openOrRequest(u);}}
 public void onRequestPermissionsResult(int r,String[] p,int[] g){super.onRequestPermissionsResult(r,p,g);if(r!=STORAGE)return;Uri u=pendingUri;pendingUri=null;if(u!=null){loading("Opening EPUB…");openAsync(u);return;}if(pendingPick){pendingPick=false;doPick();}}
 void openOrRequest(Uri u){if(u==null){home("No file selected.");return;}if(!canReadStorage()){pendingUri=u;requestPermissions(new String[]{android.Manifest.permission.READ_EXTERNAL_STORAGE},STORAGE);return;}loading("Opening EPUB…");openAsync(u);}
 InputStream openInput(Uri u)throws Exception{String s=u.getScheme();if(s==null||"file".equalsIgnoreCase(s)){String p=u.getPath();if(p==null)throw new FileNotFoundException("Missing file path");return new FileInputStream(new File(p));}InputStream in=getContentResolver().openInputStream(u);if(in==null)throw new FileNotFoundException("Cannot read selected file");return in;}
 void openAsync(final Uri u){new Thread(()->{try{del(root);root.mkdirs();File z=new File(root,"book.epub"),dir=new File(root,"x");dir.mkdirs();InputStream in=openInput(u);copy(in,new FileOutputStream(z));unzip(z,dir);parse(dir);saveList();chap=0;getPreferences(0).edit().putInt("chap",0).putInt("off",0).apply();runOnUiThread(()->show(0,0));}catch(final Throwable e){runOnUiThread(()->home("Could not open EPUB: "+err(e)));}}).start();}
 void show(int c,int off){if(spine.isEmpty()){home("No readable chapters.");return;}chap=Math.max(0,Math.min(c,spine.size()-1));try{String s=plain(read(spine.get(chap)));reader=new Reader(this,s,off);setContentView(reader);}catch(Throwable e){home("Could not read chapter: "+err(e));}}
 String plain(String s){s=s.replaceAll("(?is)<(script|style)\\b[^>]*>.*?</\\1\\s*>"," ");s=s.replaceAll("(?is)<rt\\b[^>]*>.*?</rt\\s*>","");s=s.replaceAll("(?i)<br\\s*/?>","\\n");s=s.replaceAll("(?i)</(p|div|h[1-6]|li|blockquote)\\s*>","\\n");s=s.replaceAll("(?is)<[^>]+>","");s=s.replace("&nbsp;"," ").replace("&#160;"," ").replace("&lt;","<").replace("&gt;",">").replace("&quot;","\"").replace("&apos;","'").replace("&amp;","&");s=s.replaceAll("[ \\t\\x0B\\f]+"," ").replaceAll("\\n{3,}","\\n\\n");return s.trim();}
 void next(){if(reader==null)return;if(reader.next()){save();return;}if(chap+1<spine.size()){chap++;show(chap,0);save();}}
 void prev(){if(reader==null)return;if(reader.prev()){save();return;}if(chap>0){chap--;try{String s=plain(read(spine.get(chap)));int cap=reader.capacity();show(chap,Math.max(0,s.length()-cap));save();}catch(Exception e){}}}
 void save(){if(reader!=null)getPreferences(0).edit().putInt("chap",chap).putInt("off",reader.off).apply();}
 public boolean onKeyDown(int k,KeyEvent e){if(reader!=null&&(k==KeyEvent.KEYCODE_VOLUME_DOWN||k==KeyEvent.KEYCODE_PAGE_DOWN||k==KeyEvent.KEYCODE_DPAD_LEFT)){next();return true;}if(reader!=null&&(k==KeyEvent.KEYCODE_VOLUME_UP||k==KeyEvent.KEYCODE_PAGE_UP||k==KeyEvent.KEYCODE_DPAD_RIGHT)){prev();return true;}if(k==KeyEvent.KEYCODE_MENU){save();home("Choose another book");return true;}return super.onKeyDown(k,e);}
 public void onBackPressed(){if(reader!=null){save();home("Position saved");}else super.onBackPressed();}
 void parse(File base)throws Exception{spine.clear();XmlPullParserFactory f=XmlPullParserFactory.newInstance();f.setNamespaceAware(false);XmlPullParser p=f.newPullParser();File c=new File(base,"META-INF/container.xml");p.setInput(new FileInputStream(c),null);String op=null;for(int e=p.getEventType();e!=XmlPullParser.END_DOCUMENT;e=p.next())if(e==XmlPullParser.START_TAG&&"rootfile".equals(local(p.getName()))){op=attr(p,"full-path");break;}if(op==null)throw new Exception("No OPF");File of=child(base,Uri.decode(op));HashMap<String,String> m=new HashMap<>();ArrayList<String> o=new ArrayList<>();p=f.newPullParser();p.setInput(new FileInputStream(of),null);for(int e=p.getEventType();e!=XmlPullParser.END_DOCUMENT;e=p.next())if(e==XmlPullParser.START_TAG){String n=local(p.getName());if("item".equals(n)){String id=attr(p,"id"),h=attr(p,"href");if(id!=null&&h!=null)m.put(id,h);}if("itemref".equals(n)){String id=attr(p,"idref");if(id!=null)o.add(id);}}for(String id:o){String h=m.get(id);if(h==null)continue;int q=h.indexOf('#');if(q>=0)h=h.substring(0,q);File x=new File(of.getParentFile(),Uri.decode(h)).getCanonicalFile();String bp=base.getCanonicalPath()+File.separator;if(x.isFile()&&x.getPath().startsWith(bp))spine.add(x);}if(spine.isEmpty())throw new Exception("No readable spine");}
 static String local(String s){int i=s==null?-1:s.indexOf(':');return i<0?s:s.substring(i+1);} static String attr(XmlPullParser p,String n){for(int i=0;i<p.getAttributeCount();i++)if(n.equals(local(p.getAttributeName(i))))return p.getAttributeValue(i);return null;}
 static File child(File b,String r)throws Exception{File f=new File(b,r).getCanonicalFile();String p=b.getCanonicalPath()+File.separator;if(!f.getPath().startsWith(p))throw new Exception("Unsafe EPUB path");return f;}
 void unzip(File z,File out)throws Exception{String base=out.getCanonicalPath()+File.separator;ZipInputStream in=new ZipInputStream(new BufferedInputStream(new FileInputStream(z)));ZipEntry e;byte[] b=new byte[16384];while((e=in.getNextEntry())!=null){File f=new File(out,e.getName());if(!f.getCanonicalPath().startsWith(base))throw new Exception("Unsafe EPUB path");if(e.isDirectory())f.mkdirs();else{File p=f.getParentFile();if(p!=null)p.mkdirs();FileOutputStream o=new FileOutputStream(f);int n;while((n=in.read(b))>0)o.write(b,0,n);o.close();}in.closeEntry();}in.close();}
 void saveList()throws Exception{FileWriter w=new FileWriter(new File(root,"spine.txt"));File b=new File(root,"x");String p=b.getCanonicalPath()+File.separator;for(File f:spine)w.write(f.getCanonicalPath().substring(p.length())+"\n");w.close();}
 boolean loadList(){try{spine.clear();File b=new File(root,"x"),l=new File(root,"spine.txt");if(!l.isFile())return false;BufferedReader r=new BufferedReader(new FileReader(l));String s;while((s=r.readLine())!=null){File f=child(b,s);if(f.isFile())spine.add(f);}r.close();return !spine.isEmpty();}catch(Throwable e){return false;}}
 static void copy(InputStream i,OutputStream o)throws Exception{byte[] b=new byte[16384];int n;while((n=i.read(b))>0)o.write(b,0,n);i.close();o.close();} static String read(File f)throws Exception{BufferedReader r=new BufferedReader(new InputStreamReader(new FileInputStream(f),"UTF-8"));StringBuilder b=new StringBuilder();char[] c=new char[8192];int n;while((n=r.read(c))>0)b.append(c,0,n);r.close();return b.toString();} static void del(File f){if(f==null||!f.exists())return;if(f.isDirectory()){File[] a=f.listFiles();if(a!=null)for(File x:a)del(x);}f.delete();} static String err(Throwable e){String s=e.getMessage();return s==null?e.getClass().getSimpleName():s;}
 class Reader extends View{String s;int off,lastNext;Paint p=new Paint(Paint.ANTI_ALIAS_FLAG),ui=new Paint(Paint.ANTI_ALIAS_FLAG);float downX,downY;Reader(Context c,String s,int o){super(c);this.s=s;off=Math.max(0,Math.min(o,s.length()));setBackgroundColor(Color.WHITE);p.setColor(Color.BLACK);p.setTypeface(Typeface.create("serif",0));p.setTextSize(48);ui.setColor(0xff555555);ui.setTextSize(20);}
  protected void onDraw(Canvas c){super.onDraw(c);float top=28,right=30,bottom=getHeight()-32,cell=60,col=78,x=getWidth()-right-48,y=top+48;int i=off;while(i<s.length()&&x>20){int cp=s.codePointAt(i),n=Character.charCount(cp);if(cp=='\r'){i+=n;continue;}if(cp=='\n'){i+=n;x-=col;y=top+48;continue;}String g=new String(Character.toChars(cp));if((cp>='A'&&cp<='Z')||(cp>='a'&&cp<='z')||(cp>='0'&&cp<='9')){c.save();c.rotate(90,x+22,y-22);c.drawText(g,x,y,p);c.restore();}else c.drawText(g,x,y,p);i+=n;y+=cell;if(y>bottom){x-=col;y=top+48;}}lastNext=i;c.drawText((chap+1)+"/"+spine.size(),10,getHeight()-8,ui);}
  int capacity(){int rows=Math.max(1,(getHeight()-60)/60),cols=Math.max(1,(getWidth()-50)/78);return rows*cols;} boolean next(){if(lastNext>off&&lastNext<s.length()){off=lastNext;invalidate();return true;}return false;} boolean prev(){if(off>0){off=Math.max(0,off-capacity());invalidate();return true;}return false;} public boolean onTouchEvent(MotionEvent e){if(e.getAction()==0){downX=e.getX();downY=e.getY();return true;}if(e.getAction()==1){float dx=Math.abs(e.getX()-downX),dy=Math.abs(e.getY()-downY);if(dx<45&&dy<45){if(e.getX()<getWidth()/2f)MainActivity.this.next();else MainActivity.this.prev();}else if(dx>dy&&dx>60){if(e.getX()<downX)MainActivity.this.next();else MainActivity.this.prev();}return true;}return true;}}
}
