plugins {
    id 'com.android.application'
}

android {
    namespace 'com.mars.simpleepubreader'
    compileSdk 35

    defaultConfig {
        applicationId 'com.mars.simpleepubreader.reader4'
        minSdk 23
        targetSdk 23
        versionCode 4
        versionName '1.3-mars-reader'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    buildTypes {
        debug { minifyEnabled false }
        release { minifyEnabled false }
    }
}
